stages:
  - build
  - deploy

.build: &build
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/pavelchist2001/awesome-tagger-bot/tagger:$IMAGE_TAG . 
    - docker push $CI_REGISTRY/pavelchist2001/awesome-tagger-bot/tagger:$IMAGE_TAG

.deploy: &deploy
  image: docker:20.10.16
  stage: deploy
  before_script:
    - wget -O helm-v3.17.2-linux-amd64.tar.gz  https://get.helm.sh/helm-v3.17.2-linux-amd64.tar.gz
    - tar -zxvf helm-v3.17.2-linux-amd64.tar.gz
    - chmod 700 linux-amd64/helm
    - export APP_VERSION=$IMAGE_TAG
    - sed -i "s/APP_VERSION/${APP_VERSION}/g" ./tagger-helm/Chart.yaml
  script:
    - linux-amd64/helm upgrade tagger-helm ./tagger-helm -i --namespace=$DEPLOY_NAMESPACE --kubeconfig=$KUBECONFIG_FILE 
      --set image.tag=$IMAGE_TAG
      --set extraEnv.bot.tokenFile=$BOT_TOKEN_FILENAME
      --set extraEnv.mongodb.uri=$MONGODB_URI
      --set extraEnv.mongodb.user=$MONGODB_USER
      --set extraEnv.mongodb.pass=$MONGODB_PASS
      --set extraEnv.mongodb.db=$MONGODB_DB
      --set extraEnv.bot.debug=$BOT_DEBUG
      --set extraEnv.bot.token=$BOT_TOKEN
      --set extraEnv.kandinsky.host=$KANDINSKY_HOST
      --set extraEnv.kandinsky.key=$KANDINSKY_KEY
      --set extraEnv.kandinsky.secret=$KANDINSKY_SECRET

build_test:
  only:
    - test
  <<: *build
  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-test"

deploy_test:
  only:
    - test
  <<: *deploy
  variables:
    IMAGE_TAG: "$CI_COMMIT_SHORT_SHA-test"
    BOT_TOKEN_FILENAME: ""
    MONGODB_URI: $MONGODB_URI
    MONGODB_USER: $MONGODB_USER
    MONGODB_PASS: $MONGODB_PASS
    MONGODB_DB: $MONGODB_DB_TEST
    BOT_DEBUG: true
    BOT_TOKEN: $BOT_TOKEN_TEST
    KANDINSKY_HOST: $KANDINSKY_HOST
    KANDINSKY_KEY: $FUSION_BRAIN_API_KEY
    KANDINSKY_SECRET: $FUSION_BRAIN_SECRET_KEY
    DEPLOY_NAMESPACE: tagger-test


build_prod:
  only:
    - tags
    - /\d+\.\d+\.\d+\.\d+$/ # 1.2.3.4
  <<: *build
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG

deploy_prod:
  only:
    - tags
    - /\d+\.\d+\.\d+\.\d+$/ # 1.2.3.4
  <<: *deploy
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
    BOT_TOKEN_FILENAME: ""
    MONGODB_URI: $MONGODB_URI
    MONGODB_USER: $MONGODB_USER
    MONGODB_PASS: $MONGODB_PASS
    MONGODB_DB: $MONGODB_DB_PROD
    BOT_DEBUG: false
    BOT_TOKEN: $BOT_TOKEN_PROD
    KANDINSKY_HOST: $KANDINSKY_HOST
    KANDINSKY_KEY: $FUSION_BRAIN_API_KEY
    KANDINSKY_SECRET: $FUSION_BRAIN_SECRET_KEY
    DEPLOY_NAMESPACE: tagger-prod
