version: '3.1'

services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MPASS}
    volumes:
      - ./data/db:/data/db