version: '3.1'

services:
  mongo-local:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MPASS}
    volumes:
      - ./data/db:/data/db
  tagger-test:
    image: ${REG}:${TAG}
    restart: always
    environment:
      BOT_TOKEN_FILENAME: ${BOT_TOKEN_FILENAME}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
      MONGODB_DB: ${MONGODB_DB}
      BOT_DEBUG: ${BOT_DEBUG}
      BOT_TOKEN: ${BOT_TOKEN}
  tagger-prod:
    image: ${REG}:${TAG}
    restart: always
    environment:
      BOT_TOKEN_FILENAME: ${BOT_TOKEN_FILENAME}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
      MONGODB_DB: ${MONGODB_DB}
      BOT_DEBUG: ${BOT_DEBUG}
      BOT_TOKEN: ${BOT_TOKEN}
  mongo-prod:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    volumes:
      - ./data/db:/data/db